name: Deploy Clofast
on:
  push:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Client Image
        run: docker build --build-arg VITE_API_BASE_URL="${{ secrets.VITE_API_BASE_URL }}" -t gnaneswaryalla/clofast-client ./client
      - name: Push Client Image
        run: docker push gnaneswaryalla/clofast-client:latest

  build-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Server Image
        run: docker build -t gnaneswaryalla/clofast-server ./server
      - name: Push Server Image
        run: docker push gnaneswaryalla/clofast-server:latest

  deploy:
    needs: [build-client, build-server]
    runs-on: self-hosted
    steps:
      - name: Clean up Docker resources
        run: |
          docker system prune -af --volumes
          docker builder prune -af

      - name: Pull Client Image
        run: docker pull gnaneswaryalla/clofast-client:latest

      - name: Pull Server Image
        run: docker pull gnaneswaryalla/clofast-server:latest

      - name: Delete old Server Container
        run: docker rm -f clofast-server || true

      - name: Delete old Client Container
        run: docker rm -f clofast-client || true

      - name: Run Server Container
        run: |
          docker run -d --restart unless-stopped -p 5550:5550 --name clofast-server \
            -e MONGODB_URL="${{ secrets.MONGODB_URL }}" \
            -e PORT="${{ secrets.PORT }}" \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -e AWS_REGION="${{ secrets.AWS_REGION }}" \
            -e AWS_S3_BUCKET="${{ secrets.AWS_S3_BUCKET }}" \
            -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            -e GEMINI_API_URL="${{ secrets.GEMINI_API_URL }}" \
            -e AWS_BEDROCK_AGENT_ARN="${{ secrets.AWS_BEDROCK_AGENT_ARN }}" \
            -e AWS_BEDROCK_AGENT_ID="${{ secrets.AWS_BEDROCK_AGENT_ID }}" \
            -e AWS_BEDROCK_SESSION_ID="${{ secrets.AWS_BEDROCK_SESSION_ID }}" \
            gnaneswaryalla/clofast-server:latest

      - name: Run Client Container
        run: |
          docker run -d --restart unless-stopped -p 5173:80 --name clofast-client \
          gnaneswaryalla/clofast-client:latest
